=== mihail-jekov/XML-project-for-FMI/AircraftCarrier.dtd
<?xml version="1.0" encoding="UTF-8"?>

<!ELEMENT aircraft-carrier (name, personel, aircrafts, battles, manufacturers)>
  <!ELEMENT name (#PCDATA)>
  <!ATTLIST aircraft-carrier engine (nuclear|diesel) "nuclear">
  <!ATTLIST aircraft-carrier class CDATA #REQUIRED>
  <!ATTLIST aircraft-carrier years-of-service CDATA #IMPLIED>
  <!ELEMENT personel (soldier+)>
    <!ELEMENT soldier (first-name, last-name, gender, position, age, religion)>
      <!ATTLIST soldier id ID #REQUIRED
						aircraft IDREFS #IMPLIED
						battle IDREFS #IMPLIED>
	  <!ELEMENT first-name (#PCDATA)>
	  <!ELEMENT last-name (#PCDATA)>
      <!ELEMENT gender (#PCDATA)>
	  <!ELEMENT position (#PCDATA)>
	  <!ELEMENT age (#PCDATA)>
	  <!ELEMENT religion (#PCDATA)>
  <!ELEMENT aircrafts (aircraft+)>
    <!ELEMENT aircraft (model, cost, specifications, helicopter?)>
	  <!ATTLIST aircraft id ID #REQUIRED
	                     battle IDREFS #IMPLIED
	                     manufacturer IDREF #REQUIRED>
	  <!ATTLIST aircraft control (pilot|auto-pilot) #REQUIRED>
	  <!ATTLIST aircraft role (fighter|bomber|multirole|reconnaissance|electronic-warfare) #REQUIRED>
      <!ELEMENT model (#PCDATA)>
	  <!ELEMENT cost (#PCDATA)>
	  <!ELEMENT specifications (crew, range, weight)>
	    <!ELEMENT crew (#PCDATA)>
        <!ELEMENT range (#PCDATA)>
	    <!ELEMENT weight (#PCDATA)>
	  <!ELEMENT helicopter (main-rotor-diameter, main-rotor-area)>
	    <!ELEMENT main-rotor-diameter (#PCDATA)>
	    <!ELEMENT main-rotor-area (#PCDATA)>
  <!ELEMENT battles (battle*)>
    <!ELEMENT battle (battle-name, countries, duration, description?, units-lost)>
	  <!ATTLIST battle id ID #REQUIRED>
      <!ELEMENT battle-name (#PCDATA)>
      <!ELEMENT countries (country+)>
        <!ELEMENT country (country-name, population)>
		  <!ATTLIST country continent (europe|asia|north-america|south-america|africa|antarctica) #IMPLIED>
          <!ELEMENT country-name (#PCDATA)>
		  <!ELEMENT population (#PCDATA)>
      <!ELEMENT duration (#PCDATA)>
	  <!ELEMENT description (#PCDATA)>
	  <!ELEMENT units-lost (#PCDATA)>
  <!ELEMENT manufacturers (manufacturer*)>
    <!ELEMENT manufacturer (manufacturer-name, established, staff-count, profit)>
      <!ATTLIST manufacturer id ID #REQUIRED>
	  <!ELEMENT manufacturer-name (#PCDATA)>
	  <!ELEMENT established (#PCDATA)>
	  <!ELEMENT staff-count (#PCDATA)>
      <!ELEMENT profit (#PCDATA)>

=== mihail-jekov/XML-project-for-FMI/Valid_XML_1.xml
<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE aircraft-carrier SYSTEM "AircraftCarrier.dtd">
<?xml-stylesheet type="text/xsl" href="XML_Transformation_2.xsl"?>

<aircraft-carrier engine = "diesel" class = "Shōkaku-class" years-of-service = "1941-1944">
	<name>Shōkaku</name>
	<personel>
		<soldier id = "s1" aircraft = "a1" battle = "b1 b2 b3">
			<first-name>Такижиро</first-name>
			<last-name>Охниши</last-name>
			<gender>мъж</gender>
			<position>пилот</position>
			<age>46</age>
			<religion>шинто</religion>
		</soldier>
		<soldier id = "s2" battle = "b1 b2">
			<first-name>Исороку</first-name>
			<last-name>Ямамато</last-name>
			<gender>мъж</gender>
			<position>адмирал</position>
			<age>58</age>
			<religion>шинто</religion>
		</soldier>
		<soldier id = "s3" battle = "b2 b3 b4">
			<first-name>Нобутаке</first-name>
			<last-name>Кондо</last-name>
			<gender>мъж</gender>
			<position>адмирал</position>
			<age>66</age>
			<religion>будизъм</religion>
		</soldier>
		<soldier id = "s4" battle = "a1">
			<first-name>Чучи</first-name>
			<last-name>Нагумо</last-name>
			<gender>мъж</gender>
			<position>адмирал</position>
			<age>57</age>
			<religion>шинто</religion>
		</soldier>
		<soldier id = "s5" aircraft = "a1">
			<first-name>Тамон</first-name>
			<last-name>Ямагучи</last-name>
			<gender>мъж</gender>
			<position>адмирал</position>
			<age>49</age>
			<religion>шинто</religion>
		</soldier>
		<soldier id = "s6" aircraft = "a1">
			<first-name>Руйсако</first-name>
			<last-name>Янагимото</last-name>
			<gender>мъж</gender>
			<position>адмирал</position>
			<age>47</age>
			<religion>будизъм</religion>
		</soldier>
	</personel>
	<aircrafts>
		<aircraft id = "a1" control = "pilot" role = "fighter" manufacturer="m1" battle = "b2 b4 b5">
			<model>Мицубиши A6M Zero</model>
			<cost>$200000</cost>
			<specifications>
				<crew>1</crew>
				<range>3105 км</range>
				<weight>1680 кг</weight>
			</specifications>
		</aircraft>
		<aircraft id = "a2" control = "pilot" role = "bomber" manufacturer="m2" battle = "b1 b2 b3 b4">
			<model>Aichi D3A1</model>
			<cost>$200000</cost>
			<specifications>
				<crew>2</crew>
				<range>1472 км</range>
				<weight>3650 кг</weight>
			</specifications>
		</aircraft>
		<aircraft id = "a3" control = "pilot" role = "bomber" manufacturer="m3" battle = "b1 b3 b5">
			<model>Nakajima B5N</model>
			<cost>$220000</cost>
			<specifications>
				<crew>3</crew>
				<range>1992 км</range>
				<weight>2279 кг</weight>
			</specifications>
		</aircraft>
	</aircrafts>
	<battles>
		<battle id="b1">
			<battle-name>Пърл Харбър</battle-name>
			<countries>
				<country continent="asia">
					<country-name>Съединени американски щати</country-name>
					<population>313 милиона</population>
				</country>
			</countries>
			<duration>един ден</duration>
			<description>Нападението над Пърл Харбър е изненадваща въздушна атака на японския Императорски флот срещу американската военноморска база при Пърл Харбър, Хаваи, извършена сутринта на 7 декември 1941 г.
				Без предварително обявяване на война базата е атакувана от 353 японски бойни самолети, бомбардировачи и торпедоносци на две вълни, изстрелвани от шест самолетоносача. Унищожена е голяма част от американския тихоокеански военноморски флот.
				Атаката е повратна точка в развоя на Втората световна война, тъй като става повод за влизането на САЩ, която да този момент е неутрална, във войната. Въпреки, че атаката причинява на САЩ значителни военни загуби, тя се оказва с фатални последствия за Япония. На следващия ден (8 декември) САЩ обявява война на Япония.
			</description>
			<units-lost></units-lost>
		</battle>
		<battle id="b2">
			<battle-name>Битка при Мидуей</battle-name>
			<countries>
				<country continent="asia">
					<country-name>Съединени американски щати</country-name>
					<population>313 милиона</population>
				</country>
			</countries>
			<duration>три дни</duration>
			<description>
				Битката при атола Мидуей се състои на 4 юни 1942 година и е една от най-значителните морски битки на Втората световна война. Флотът на САЩ побеждава обединения флот на Япония, който атакува атола Мидуей. Битката бележи повратен момент във войната в Тихия океан. Обединеният флот на Япония губи 4 тежки самолетоносача, 250 самолета и най-добрите си пилоти, с което загубва възможностите си да действа извън зоната на прикритие на бреговата авиация.
			</description>
			<units-lost></units-lost>
		</battle>
		<battle id="b3">
			<battle-name>Битката при островите Санта Круз</battle-name>
			<countries>
				<country continent="asia">
					<country-name>Съединени американски щати</country-name>
					<population>313 милиона</population>
				</country>
			</countries>
			<duration>три дни</duration>
			<description>
				Битката при атола Мидуей се състои на 4 юни 1942 година и е една от най-значителните морски битки на Втората световна война. Флотът на САЩ побеждава обединения флот на Япония, който атакува атола Мидуей. Битката бележи повратен момент във войната в Тихия океан. Обединеният флот на Япония губи 4 тежки самолетоносача, 250 самолета и най-добрите си пилоти, с което загубва възможностите си да действа извън зоната на прикритие на бреговата авиация.
			</description>
			<units-lost></units-lost>
		</battle>
		<battle id="b4">
			<battle-name>Битката за Иво Джима</battle-name>
			<countries>
				<country continent="asia">
					<country-name>Съединени американски щати</country-name>
					<population>313 милиона</population>
				</country>
			</countries>
			<duration>три дни</duration>
			<description>
				Битката при атола Мидуей се състои на 4 юни 1942 година и е една от най-значителните морски битки на Втората световна война. Флотът на САЩ побеждава обединения флот на Япония, който атакува атола Мидуей. Битката бележи повратен момент във войната в Тихия океан. Обединеният флот на Япония губи 4 тежки самолетоносача, 250 самолета и най-добрите си пилоти, с което загубва възможностите си да действа извън зоната на прикритие на бреговата авиация.
			</description>
			<units-lost></units-lost>
		</battle>
		<battle id="b5">
			<battle-name>Битка в Коралово море</battle-name>
			<countries>
				<country continent="asia">
					<country-name>Австралия</country-name>
					<population>22117876</population>
				</country>
			</countries>
			<duration>четири дни</duration>
			<description>
				Битката в Коралово море е морско сражение, състояло се на 6 - 8 май 1942 г. в Тихия океан между сили на Япония и САЩ през Втората световна война. Това е първата в историята морска битка, в която от двете страни участва само палубна авиация.
			</description>
			<units-lost></units-lost>
		</battle>
	</battles>
	<manufacturers>
		<manufacturer id="m1">
			<manufacturer-name>Mitsubishi Heavy Industries</manufacturer-name>
			<established>1914</established>
			<staff-count>63500</staff-count>
			<profit>$300 милиона</profit>
		</manufacturer>
		<manufacturer id="m2">
			<manufacturer-name>Aichi Aircraft Company</manufacturer-name>
			<established>1898</established>
			<staff-count>4000</staff-count>
			<profit>$300 милиона</profit>
		</manufacturer>
		<manufacturer id="m3">
			<manufacturer-name>Nakajima Aircraft Company</manufacturer-name>
			<established>1918</established>
			<staff-count>4000</staff-count>
			<profit>$300 милиона</profit>
		</manufacturer>
	</manufacturers>
</aircraft-carrier>

=== mihail-jekov/XML-project-for-FMI/Valid_XML_3.xml
<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE aircraft-carrier SYSTEM "AircraftCarrier.dtd">
<?xml-stylesheet type="text/xsl" href="HTML_Transformation_3.xsl"?>

<aircraft-carrier engine = "nuclear" class = "Шарл дьо Гол" years-of-service = "2001-present">
	<name>Шарл дьо Гол</name>
	<personel>
		<soldier id = "s1" aircraft = "a6">
			<first-name>Франсоа</first-name>
			<last-name>Лебьов</last-name>
			<gender>мъж</gender>
			<position>адмирал</position>
			<age>36</age>
			<religion>християнин</religion>
		</soldier>
	</personel>
	<aircrafts>
		<aircraft id = "a12" control = "pilot" role = "fighter" manufacturer = "m1">
			<model>Rafale</model>
			<cost>74 милиона евро</cost>
			<specifications>
				<crew>1-2</crew>
				<range>3700 км</range>
				<weight>9500 кг</weight>
			</specifications>
		</aircraft>
		<aircraft id = "a13" control = "pilot" role = "bomber" manufacturer = "m1">
			<model>Super Étendard</model>
			<cost>12 милиона долара</cost>
			<specifications>
				<crew>1</crew>
				<range>1820 км</range>
				<weight>6500 кг</weight>
			</specifications>
		</aircraft>
		<aircraft id = "a15" control = "pilot" role = "bomber" manufacturer = "m4">
			<model>SA 365 Dauphin 2</model>
			<cost>10 милиона долара</cost>
			<specifications>
				<crew>1-2</crew>
				<range>827 км</range>
				<weight>2411 кг</weight>
			</specifications>
			<helicopter>
				<main-rotor-diameter>11.94 м</main-rotor-diameter>
				<main-rotor-area>111.98 м2</main-rotor-area>
			</helicopter>
		</aircraft>
		<aircraft id = "a6" control = "pilot" role = "fighter" manufacturer="m1">
			<model>F-22 Raptor</model>
			<cost>$150 милиона</cost>
			<specifications>
				<crew>1</crew>
				<range>3320 км</range>
				<weight>19700 кг</weight>
			</specifications>
		</aircraft>
		<aircraft id = "a14" control = "pilot" role = "bomber" manufacturer = "m3">
			<model>E-2 Hawkeye</model>
			<cost>176 милиона долара</cost>
			<specifications>
				<crew>5</crew>
				<range>2708 км</range>
				<weight>18090 кг</weight>
			</specifications>
		</aircraft>
		<aircraft id = "a16" control = "pilot" role = "bomber" manufacturer = "m4">
			<model>EC 725 Super Cougar</model>
			<cost>24.5 милиона долара</cost>
			<specifications>
				<crew>1-2</crew>
				<range>857 км</range>
				<weight>5330 кг</weight>
			</specifications>
			<helicopter>
				<main-rotor-diameter>16.20 м</main-rotor-diameter>
				<main-rotor-area>206.1 м2</main-rotor-area>
			</helicopter>
		</aircraft>
	</aircrafts>
	<battles>
	</battles>
	<manufacturers>
		<manufacturer id="m1">
			<manufacturer-name>Dassault Aviation</manufacturer-name>
			<established>1929</established>
			<staff-count>11600</staff-count>
			<profit>$487 милиона</profit>
		</manufacturer>
		<manufacturer id="m2">
			<manufacturer-name>Lockheed Martin</manufacturer-name>
			<established>1995</established>
			<staff-count>116000</staff-count>
			<profit>$2.981 милярда</profit>
		</manufacturer>
		<manufacturer id="m3">
			<manufacturer-name>Northrop Grumman</manufacturer-name>
			<established>1994</established>
			<staff-count>68100</staff-count>
			<profit>$1.952 милярда</profit>
		</manufacturer>
		<manufacturer id="m4">
			<manufacturer-name>Airbus Helicopters</manufacturer-name>
			<established>1992</established>
			<staff-count>23000</staff-count>
			<profit>$6.3 милярда</profit>
		</manufacturer>
	</manufacturers>
</aircraft-carrier>

=== mihail-jekov/XML-project-for-FMI/Valid_XML_4.xml
<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE aircraft-carrier SYSTEM "AircraftCarrier.dtd">
<?xml-stylesheet type="text/xsl" href="XML_Transformation_1.xsl"?>

<aircraft-carrier engine = "nuclear" class = "USS Nimitz" years-of-service = "1975-present">
	<name>Нимиц</name>
	<personel>
		<soldier id = "s1">
			<first-name>Хари</first-name>
			<last-name>Харис</last-name>
			<gender>мъж</gender>
			<position>адмирал</position>
			<age>58</age>
			<religion>шинто</religion>
		</soldier>
	</personel>
	<aircrafts>
		<aircraft id = "a4" control = "pilot" role = "fighter" manufacturer="m5" battle = "b2">
			<model>F-15 Eagle</model>
			<cost>$28 милиона</cost>
			<specifications>
				<crew>1</crew>
				<range>5550 км</range>
				<weight>127000 кг</weight>
			</specifications>
		</aircraft>
		<aircraft id = "a5" control = "pilot" role = "multirole" manufacturer="m4" battle = "b1 b2">
			<model>F-16 Fighting Falcon</model>
			<cost>$14.6 милиона</cost>
			<specifications>
				<crew>1</crew>
				<range>4420 км</range>
				<weight>8570 кг</weight>
			</specifications>
		</aircraft>
		<aircraft id = "a6" control = "pilot" role = "fighter" manufacturer="m1">
			<model>F-22 Raptor</model>
			<cost>$150 милиона</cost>
			<specifications>
				<crew>1</crew>
				<range>3320 км</range>
				<weight>19700 кг</weight>
			</specifications>
		</aircraft>
		<aircraft id = "a7" control = "pilot" role = "bomber" manufacturer="m3" battle = "b1 b2">
			<model>B-2 Spirit</model>
			<cost>$737 милиона</cost>
			<specifications>
				<crew>2</crew>
				<range>11100 км</range>
				<weight>71700 кг</weight>
			</specifications>
		</aircraft>
		<aircraft id = "a8" control = "pilot" role = "electronic-warfare" manufacturer="m2" battle = "b1 b2">
			<model>EA-18G Growler</model>
			<cost>$68.2 милиона</cost>
			<specifications>
				<crew>2</crew>
				<range>2346 км</range>
				<weight>15011 кг</weight>
			</specifications>
		</aircraft>
		<aircraft id = "a9" control = "pilot" role = "multirole" manufacturer="m1">
			<model>F-35 Lightning II</model>
			<cost>142 милиона долара</cost>
			<specifications>
				<crew>1</crew>
				<range>2220 км</range>
				<weight>13199 кг</weight>
			</specifications>
		</aircraft>
		<aircraft id = "a10" control = "pilot" role = "reconnaissance" manufacturer="m1" battle = "b1">
			<model>U-2</model>
			<cost>200 милиона долара</cost>
			<specifications>
				<crew>1</crew>
				<range>10300 км</range>
				<weight>6760 кг</weight>
			</specifications>
		</aircraft>
	</aircrafts>
	<battles>
		<battle id="b1">
			<battle-name>Война в Персийския залив</battle-name>
			<countries>
				<country continent="asia">
					<country-name>Ирак</country-name>
					<population>31.2 милиона</population>
				</country>
			</countries>
			<duration>210 дни</duration>
			<description>
				Войната в Персийския залив е конфликт между Ирак и обединените (коалиционни) сили на 34 държави, водени от САЩ. Войната започва с иракската инвазия в Кувейт през август 1990 г. Резултатът от войната е убедителната победа на коалиционните сили, които изтласкват иракските сили от Кувейт на цената на минимални жертви. Главните битки по земя и въздух се водят на територията на Ирак, Кувейт и съседна Саудитска Арабия. Войната не обхваща други страни, въпреки че иракски ракети засягат израелски градове.
			</description>
			<units-lost></units-lost>
		</battle>
		<battle id="b2">
			<battle-name>Войната в Ирак</battle-name>
			<countries>
				<country continent="asia">
					<country-name>Ирак</country-name>
					<population>31.2 милиона</population>
				</country>
			</countries>
			<duration>8 години и 8 месеца</duration>
			<units-lost></units-lost>
		</battle>
	</battles>
	<manufacturers>
		<manufacturer id="m2">
			<manufacturer-name>Boeing</manufacturer-name>
			<established>1916</established>
			<staff-count>168421</staff-count>
			<profit>$4.585 милярда</profit>
		</manufacturer>
		<manufacturer id="m1">
			<manufacturer-name>Lockheed Martin Aeronautics</manufacturer-name>
			<established>1995</established>
			<staff-count>116000</staff-count>
			<profit>$2.981 милярда</profit>
		</manufacturer>
		<manufacturer id="m3">
			<manufacturer-name>Northrop Grumman</manufacturer-name>
			<established>1994</established>
			<staff-count>68100</staff-count>
			<profit>1.952 милярда</profit>
		</manufacturer>
		<manufacturer id="m4">
			<manufacturer-name>General Dynamics</manufacturer-name>
			<established>1899</established>
			<staff-count>92200</staff-count>
			<profit>31.513 милярда</profit>
		</manufacturer>
		<manufacturer id="m5">
			<manufacturer-name>McDonnell Douglas</manufacturer-name>
			<established>1967</established>
			<staff-count>50000</staff-count>
			<profit>$20.30 милярда</profit>
		</manufacturer>
	</manufacturers>
</aircraft-carrier>

=== mihail-jekov/XML-project-for-FMI/Valid_XML_2.xml
<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE aircraft-carrier SYSTEM "AircraftCarrier.dtd">
<?xml-stylesheet type="text/xsl" href="HTML_Transformation_2.xsl"?>

<aircraft-carrier engine = "diesel" class = "Yorktown-class" years-of-service = "1938-1947">
	<name>USS „Ентърпрайз“ (CV-6)</name>
	<personel>
		<soldier id = "s1" battle = "b1 b2 b4 b5">
			<first-name>Честър</first-name>
			<last-name>Нимитц</last-name>
			<gender>мъж</gender>
			<position>адмирал на флоата</position>
			<age>57</age>
			<religion>християнин</religion>
		</soldier>
		<soldier id = "s2" battle = "b5">
			<first-name>Франк</first-name>
			<last-name>Флетчър</last-name>
			<gender>мъж</gender>
			<position>адмирал</position>
			<age>57</age>
			<religion>християнин</religion>
		</soldier>
		<soldier id = "s3" battle = "b2 b3">
			<first-name>Реймънд</first-name>
			<last-name>Шпруанс</last-name>
			<gender>мъж</gender>
			<position>адмирал</position>
			<age>56</age>
			<religion>християнин</religion>
		</soldier>
		<soldier id = "s4" battle = "b1 b4">
			<first-name>Марк</first-name>
			<last-name>Митчър</last-name>
			<gender>мъж</gender>
			<position>адмирал</position>
			<age>55</age>
			<religion>християнин</religion>
		</soldier>
		<soldier id = "s5" battle = "b1 b3">
			<first-name>Томас</first-name>
			<last-name>Кинкейд</last-name>
			<gender>мъж</gender>
			<position>адмирал</position>
			<age>54</age>
			<religion>християнин</religion>
		</soldier>
	</personel>
	<aircrafts>
		<aircraft id = "a1" control = "pilot" role = "fighter" manufacturer="m1">
			<model>BTD Destroyer</model>
			<cost>$200000</cost>
			<specifications>
				<crew>1</crew>
				<range>1098 км</range>
				<weight>5244 кг</weight>
			</specifications>
		</aircraft>
	</aircrafts>
	<battles>
		<battle id="b1">
			<battle-name>Пърл Харбър</battle-name>
			<countries>
				<country continent="asia">
					<country-name>Съединени американски щати</country-name>
					<population>313 милиона</population>
				</country>
			</countries>
			<duration>един ден</duration>
			<units-lost></units-lost>
		</battle>
		<battle id="b2">
			<battle-name>Битка при Мидуей</battle-name>
			<countries>
				<country continent="asia">
					<country-name>Съединени американски щати</country-name>
					<population>313 милиона</population>
				</country>
			</countries>
			<duration>три дни</duration>
			<units-lost></units-lost>
		</battle>
		<battle id="b3">
			<battle-name>Битката при островите Санта Круз</battle-name>
			<countries>
				<country continent="asia">
					<country-name>Съединени американски щати</country-name>
					<population>313 милиона</population>
				</country>
			</countries>
			<duration>три дни</duration>
			<units-lost></units-lost>
		</battle>
		<battle id="b4">
			<battle-name>Битката за Иво Джима</battle-name>
			<countries>
				<country continent="asia">
					<country-name>Съединени американски щати</country-name>
					<population>313 милиона</population>
				</country>
			</countries>
			<duration>три дни</duration>
			<units-lost></units-lost>
		</battle>
		<battle id="b5">
			<battle-name>Битка в Коралово море</battle-name>
			<countries>
				<country continent="asia">
					<country-name>Австралия</country-name>
					<population>22117876</population>
				</country>
			</countries>
			<duration>четири дни</duration>
			<units-lost></units-lost>
		</battle>
	</battles>
	<manufacturers>
		<manufacturer id="m1">
			<manufacturer-name>Дъглас</manufacturer-name>
			<established>1921</established>
			<staff-count>25500</staff-count>
			<profit>$500 милиона</profit>
		</manufacturer>
	</manufacturers>
</aircraft-carrier>

=== mihail-jekov/XML-project-for-FMI/Valid_XML_5.xml
<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE aircraft-carrier SYSTEM "AircraftCarrier.dtd">
<?xml-stylesheet type="text/xsl" href="TXT_Transformation_2.xsl"?>

<aircraft-carrier engine = "nuclear" class = "USS Nimitz" years-of-service = "1975-present">
	<name>Мидуей</name>
	<personel>
		<soldier id = "s1" aircraft = "a1">
			<first-name>Хенри</first-name>
			<last-name>Роджърс</last-name>
			<gender>мъж</gender>
			<position>адмирал</position>
			<age>48</age>
			<religion>християнин</religion>
		</soldier>
		<soldier id = "s2" aircraft = "a2" battle = "b2">
			<first-name>Кери</first-name>
			<last-name>Уилямс</last-name>
			<gender>жена</gender>
			<position>пилот</position>
			<age>28</age>
			<religion>християнин</religion>
		</soldier>
		<soldier id = "s3" aircraft = "a1" battle = "b1">
			<first-name>Диана</first-name>
			<last-name>Уилямс</last-name>
			<gender>жена</gender>
			<position>пилот</position>
			<age>29</age>
			<religion>християнин</religion>
		</soldier>
		<soldier id = "s4" aircraft = "a2">
			<first-name>Роджър</first-name>
			<last-name>Макгрегър</last-name>
			<gender>мъж</gender>
			<position>пилот</position>
			<age>25</age>
			<religion>християнин</religion>
		</soldier>
		<soldier id = "s8">
			<first-name>Джордж</first-name>
			<last-name>Кенеди</last-name>
			<gender>мъж</gender>
			<position>инструктор</position>
			<age>25</age>
			<religion>християнин</religion>
		</soldier>
		<soldier id = "s5" aircraft = "a1">
			<first-name>Джонатан</first-name>
			<last-name>Морз</last-name>
			<gender>мъж</gender>
			<position>пилот</position>
			<age>28</age>
			<religion>християнин</religion>
		</soldier>
		<soldier id = "s6" aircraft = "a3" battle = "b1 b2">
			<first-name>Грегъри</first-name>
			<last-name>Прат</last-name>
			<gender>мъж</gender>
			<position>пилот</position>
			<age>54</age>
			<religion>християнин</religion>
		</soldier>
		<soldier id = "s7" aircraft = "a2" battle = "b2">
			<first-name>Джонатан</first-name>
			<last-name>Морз</last-name>
			<gender>мъж</gender>
			<position>инструктор</position>
			<age>28</age>
			<religion>християнин</religion>
		</soldier>
	</personel>
	<aircrafts>
		<aircraft id = "a1" control = "pilot" role = "fighter" manufacturer="m1" battle = "b1 b2">
			<model>F-15 Eagle</model>
			<cost>$28 милиона</cost>
			<specifications>
				<crew>1</crew>
				<range>5550 км</range>
				<weight>127000 кг</weight>
			</specifications>
		</aircraft>
		<aircraft id = "a2" control = "pilot" role = "multirole" manufacturer="m2" battle = "b1">
			<model>F-16 Fighting Falcon</model>
			<cost>$14.6 милиона</cost>
			<specifications>
				<crew>1</crew>
				<range>4420 км</range>
				<weight>8570 кг</weight>
			</specifications>
		</aircraft>
		<aircraft id = "a3" control = "pilot" role = "fighter" manufacturer="m1" battle = "b2">
			<model>F-22 Raptor</model>
			<cost>$150 милиона</cost>
			<specifications>
				<crew>1</crew>
				<range>3320 км</range>
				<weight>19700 кг</weight>
			</specifications>
		</aircraft>
	</aircrafts>
	<battles>
		<battle id="b1">
			<battle-name>Война в Персийския залив</battle-name>
			<countries>
				<country continent="asia">
					<country-name>Ирак</country-name>
					<population>31.2 милиона</population>
				</country>
			</countries>
			<duration>210 дни</duration>
			<description>
				Войната в Персийския залив е конфликт между Ирак и обединените (коалиционни) сили на 34 държави, водени от САЩ. Войната започва с иракската инвазия в Кувейт през август 1990 г. Резултатът от войната е убедителната победа на коалиционните сили, които изтласкват иракските сили от Кувейт на цената на минимални жертви. Главните битки по земя и въздух се водят на територията на Ирак, Кувейт и съседна Саудитска Арабия. Войната не обхваща други страни, въпреки че иракски ракети засягат израелски градове.
			</description>
			<units-lost></units-lost>
		</battle>
		<battle id="b2">
			<battle-name>Пустинен щит</battle-name>
			<countries>
				<country continent="asia">
					<country-name>Ирак</country-name>
					<population>31.2 милиона</population>
				</country>
			</countries>
			<duration>130 дни</duration>
			<units-lost></units-lost>
		</battle>
	</battles>
	<manufacturers>
		<manufacturer id="m2">
			<manufacturer-name>General Dynamics</manufacturer-name>
			<established>1899</established>
			<staff-count>92200</staff-count>
			<profit>31.513 милярда</profit>
		</manufacturer>
		<manufacturer id="m1">
			<manufacturer-name>McDonnell Douglas</manufacturer-name>
			<established>1967</established>
			<staff-count>50000</staff-count>
			<profit>$20.30 милярда</profit>
		</manufacturer>
	</manufacturers>
</aircraft-carrier>
